### ISSUE TITLE
unable to download data for scene 2019_02_27/0003

### ISSUE THREAD

**Issue by janesjanes** [mpitropov/cadc_devkit#1]
Hi,

Thanks for sharing this cool dataset,

I notice that the raw.zip from http://wiselab.uwaterloo.ca/cadcd_data/2019_02_27/0003/raw.zip can't really be extracted (getting error about it not being a zip file). Can you check if there's something wrong with the file and maybe reupload it if so?

Thanks!

**Comment by mpitropov** [comment]
Hi, I think there was an issue during compression. I've reuploaded that file.
