### ISSUE TITLE
Can'f find annotations file

### ISSUE THREAD

**Issue by cygerts** [mpitropov/cadc_devkit#10]
Hi,
Thanks for great work.
I just downloaded full dataset but cannot really find any of the 2d or 3d annotations files ("3d_ann.json", "2d_annotations.json") you use in run(2D)_demo_tracklet.py.
Am I missing sth?

**Comment by mpitropov** [comment]
Hi, right now we allow for downloading of the 3d annotations only. There is a variable called "labeled" in the download script that you would have to set to True to downloaded the labeled data with the 3d annotations. labelled downloading should be the default and I updated the script.
https://github.com/mpitropov/cadc_devkit/blob/421bbf128a7aafda66159e66689f0c9436e94eda/download_cadcd.py#L36
