### ISSUE TITLE
Error while downloading 

### ISSUE THREAD

**Issue by FirasAbdennadher** [mpitropov/cadc_devkit#12]
Hi, Thanks for your sharing.

While am downloading the dataset an error occurred.
![qq](https://user-images.githubusercontent.com/24193920/105610045-2949e000-5d7b-11eb-8a41-1a1c0348b027.png)

**Comment by mpitropov** [comment]
Have you tried adding any print statements to debug this? From the error it is not clear what the issue is. Could you output the ann_3d_url variable?

Potentially an annotation file has been corrupted and I need to re-upload it.
