### ISSUE TITLE
Error when running run_demo_lidar_bev.py

### ISSUE THREAD

**Issue by ZiadElmassik** [mpitropov/cadc_devkit#13]
On line 123, I'm getting: AttributeError: 'scipy.spatial.transform.rotation.Rotation' object has no attribute 'as_dcm'. The Scipy version I'm using is 1.6.3.

**Comment by mpitropov** [comment]
It seems like they didn't deprecate that function, but they renamed it. https://docs.scipy.org/doc/scipy/reference/release.1.4.0.html#scipy-deprecations

For now, you can change 'as_dcm' to 'as_matrix' and it should work for that version of scipy. I'll have to add this change to the code.

**Comment by ZiadElmassik** [comment]
I've modified line 123 to as_matrix and it worked. Thank you!

**Comment by rightchose** [comment]
https://github.com/mpitropov/cadc_devkit/blob/ca81ed53d9d5bdcb3b9cb4c19080826ba07934e6/run_demo_tracklets.py#L51
It has the same error.

**Comment by mpitropov** [comment]
I've updated the code with the fix
