### ISSUE TITLE
How to convert to ROSBag?

### ISSUE THREAD

**Issue by ZiadElmassik** [mpitropov/cadc_devkit#14]
Hello, I'm trying to convert the dataset into a ROS Bag in order to visualize the data in rviz. Is there any way to do this?

**Comment by mpitropov** [comment]
I don't include any scripts that are dependent on ROS with this dataset. I also don't have a script like that available since all my scripts convert from ROS bags to files.

**Comment by ZiadElmassik** [comment]
I see. What about the instructions in this repo https://github.com/asvath/cadcd to convert the pcl data into rosbag? Is this repo still relevant? If so then recording the image data should be fairly easy.

**Comment by mpitropov** [comment]
That repository contains the code that I based the "run_demo_lidar_bev.py" script on. That repo is not maintained, since it was created for an earlier version of the dataset format.

I agree that you should take a look at https://github.com/asvath/cadcd/blob/master/moose2fullbag.py to base your own script on.

**Comment by ZiadElmassik** [comment]
Alright, I'll draw some inspiration from the moose2fullbag.py and the kitti2bag script to see if I can convert the 2019_02_27 dataset into a ROS Bag. Thank you very much.

**Comment by ZiadElmassik** [comment]
Hello Mathew, thank you for responding, I'm currently working on a script for converting the images from camera 00 into a ROS Bag. Could you approve of this work so far, if possible?

`import os
import cv2
import rospy
import rosbag
from datetime import datetime
from std_msgs.msg import Header
from sensor_msgs.msg import CameraInfo, Imu, PointField, NavSatFix
import sensor_msgs.point_cloud2 as pcl2
from geometry_msgs.msg import TransformStamped, TwistStamped, Transform
from cv_bridge import CvBridge
import numpy as np
import argparse
import progressbar

def save_camera_data(bag, directory , util, bridge, camera, camera_frame_id, topic, initial_time): 
	print("Exporting Camera Data")
	
#Joining directories to access images for camera 00 and timestamps
	image_dir = os.path.join(directory, 'image_00')
	image_path = os.path.join(image_dir, 'data')
	image_filenames = sorted(os.listdir(image_path))
	with open(os.path.join(image_dir, 'timestamps.txt')) as f:
		image_datetimes = map(lambda x: datetime.strptime(x[:-4], '%Y-%m-%d %H:%M:%S.%f'), f.readlines())
	
#Creating CameraInfo Topic
	calib = CameraInfo()
	calib.header.frame_id = camera_frame_id
	
#Data Obtained from calib/00.yaml
	calib.width = 1280
	calib.height = 1024
	calib.distortion_model = 'plumb_bob'
	calib.D = np.array([-0.211078226790761, 0.101157542400588, -0.000329515817247860, 0.000330423801388672, -0.0232053947325804])
	calib.K = np.array([653.956033188809, -0.235925653043616, 653.221172545916, 0, 655.540088617960, 508.73286399391, 0, 0, 1])
	calib.R = np.array([1, 0, 0, 0, 1, 0, 0, 0, 1])
	calib.P = np.array([653.956033188809, -0.235925653043616, 653.221172545916, 0, 0, 655.540088617960, 508.73286399391, 0, 0, 0, 1, 0])
	
#Iterating over images
	iterable = zip(image_datetimes, image_filenames)
	bar = progressbar.ProgressBar()
	for dt, filename in bar(iterable):
		image_filename = os.path.join(image_path, filename)
		cv_image = cv2.imread(image_filename)
		calib.height, calib.width = cv_image.shape[:2]
		encoding = "mono8" if camera in (0, 1) else "bgr8"
		
#Converting images to messages
		image_message = bridge.cv2_to_imgmsg(cv_image, encoding=encoding)
		image_message.header.frame_id = camera_frame_id
		image_message.header.stamp = rospy.Time.from_sec(float(datetime.strftime(dt, "%s.%f")))
		
#Prepating topic 
		topic_ext = "/image_raw"
		calib.header.stamp = image_message.header.stamp
		bag.write(topic + topic_ext, image_message, t = image_message.header.stamp)
		bag.write(topic + '/camera_info', calib, t = calib.header.stamp) `

**Comment by ZiadElmassik** [comment]
Hello Mathew, I thought I'd inform you. I have finally created and tested a script to convert the data from camera 00 and the corresponding pointcloud data into a rosbag.
