### ISSUE TITLE
Are the published VLP-32C point clouds the strongest or last returns?

### ISSUE THREAD

**Issue by MartinHahner** [mpitropov/cadc_devkit#16]
According to the [manual of the VLP-32C](https://icave2.cse.buffalo.edu/resources/sensor-modeling/VLP32CManual.pdf) (section 6.2), the LiDAR sensor is capable of collecting _strongest_ and/or _last_ returns.

After looking at the LiDAR point clouds in the 
`<date>/<sequence>/lidar_points` folders
I assume those are the _strongest_ returns.

Can you please clarify if my assumption is correct and you indeed released the strongest returns?

**Comment by mpitropov** [comment]
I believe that we have it set to strongest return, but the only way for me to check for sure is by accessing the lidar webpage since it is not set in the config file for the driver.

I'll leave this issue open while I confirm the setting.

**Comment by mpitropov** [comment]
The lidar is set to strongest returns

**Comment by MartinHahner** [comment]
Thank you for clarifying.
