### ISSUE TITLE
Snow Points Removed Details

### ISSUE THREAD

**Issue by MartinHahner** [mpitropov/cadc_devkit#24]
@mpitropov 

Hi Matthew,
May I ask what number is reported under **Snow Points Removed** in [cadc_dataset_route_stats.csv](https://github.com/mpitropov/cadc_devkit/blob/master/cadc_dataset_route_stats.csv#L1).
I understand that [DROR](https://github.com/nickcharron/lidar_snow_removal) is applied to get this number,
but is it the average number of points removed over the whole sequence?
Or is it the number of points removed in the first scene of a sequence?

Can you please clarrify what exactly it is? 

I am trying to re-implement DROR (because I don't have ROS) to reproduce the numbers.
Then I want to create sub-sets of another dataset accordingly, that's why I am asking for the details.

Thanks!

**Comment by mpitropov** [comment]
Good question, I have DROR already implemented in python so you can take look into the script in: https://github.com/mpitropov/cadc_devkit/tree/master/other

The number of points removed is only on the first frame in the sequence.

**Comment by MartinHahner** [comment]
> https://github.com/mpitropov/cadc_devkit/tree/master/other

Thanks, that's great.

**Comment by MartinHahner** [comment]
I was able to reproduce the numbers! Thanks a lot.

**Comment by MartinHahner** [comment]
Here is my [log file](https://github.com/mpitropov/cadc_devkit/files/6919270/CADC.log) with additional statistics in case anyone is wondering.
`1st_snow` is the reproduced number stated in [cadc_dataset_route_stats.csv](https://github.com/mpitropov/cadc_devkit/blob/master/cadc_dataset_route_stats.csv#L1).
