### ISSUE TITLE
[Question] Win7 PermissionError: [WinError 32] The process cannot access the file...

### ISSUE THREAD

**Issue by jayhsu0627** [mpitropov/cadc_devkit#3]
Hi @mpitropov 
In my Win7 cmd terminal, I encounter an error when running your original code download_cadcd.py.
`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process`

![image](https://user-images.githubusercontent.com/31528202/75840165-96702200-5e05-11ea-8074-b72940fd638e.png)

After [google](https://stackoverflow.com/questions/27215462/permissionerror-winerror-32-the-process-cannot-access-the-file-because-it-is), I found after` line 57` of `download_cadcd.py` you didn't close the zip function.
So I add `zip.close()` to line 58, problem solved.

![image](https://user-images.githubusercontent.com/31528202/75840092-6f195500-5e05-11ea-83e4-6906beef55fa.png)

Did you try it on windows environment? I'm not sure, am I right?

Best Regards!

**Comment by jayhsu0627** [comment]
![image](https://user-images.githubusercontent.com/31528202/75880741-ceed1b80-5e58-11ea-89ab-2007c78fece4.png)
same problem at `line 82 zip.extractall()`
add `zip.close()`

Problem Solved

**Comment by mpitropov** [comment]
Hi, thanks for pointing this out! I have only tested on Ubuntu. I've pushed an update:
https://github.com/mpitropov/cadc_devkit/commit/ae4feffae5002350f7957653f522e854a3a8016a

**Comment by jayhsu0627** [comment]
my pleasure!
