### ISSUE TITLE
Is the data collected follwing the same route?

### ISSUE THREAD

**Issue by wyzrxrs** [mpitropov/cadc_devkit#5]
Hello,
In your paper, it is mentioned that the data was collected over 3 days. 

Are they collected from the exact same route?

Where can I find the timestamps for the 75 driving sequences and GPS locations for each sequence?

Thanks very much!

**Comment by charlesyz** [comment]
if you download the labeled dataset, there are timestamps for each set of images in:
`cadcd/<DATE>/<XXXX>/labeled/<CAMERA>/timestamps.txt`

There are also novatel coordinates for each of the frames in 
`cadcd/<DATE>/<XXXX>/labeled/novatel/`
