### ISSUE TITLE
Dataset server down

### ISSUE THREAD

**Issue by Lehdari** [mpitropov/cadc_devkit#7]
Hi,

I downloaded partial dataset in June for I/O testing. Today when I proceeded to download rest of the dataset I was unable to establish a connection to the server and indeed, the [http://wiselab.uwaterloo.ca/cadcd_data/](http://wiselab.uwaterloo.ca/cadcd_data/) is unresponsive.

I would like to use the dataset in my master's thesis - would you be able to bring the server back online and maybe setup a mirror for redundancy were this to happen again in the future?

Best regards,
Miika Lehtimäki

**Comment by deeptibhegde** [comment]
Yes I am unable to download the data as well. Commenting to keep track of when the server will be back up.

**Comment by cmpute** [comment]
Also failed to download the dataset here

**Comment by mpitropov** [comment]
We should be able to get it running tomorrow but are having a bit of trouble as our IT contacts have changed.

**Comment by mpitropov** [comment]
The server is back up and running
